FROM python:3.10.10-slim-bullseye

WORKDIR /app

COPY ../../requirements.txt .

EXPOSE 8000

RUN apt-get update && apt-get upgrade -y && apt-get install -y build-essential
RUN pip install -r requirements.txt

COPY ../../ .

CMD uvicorn main:app --host 0.0.0.0 --port $PORT